[workspace]
members = ["crates/roc_host", "crates/roc_host_bin", "crates/roc_host_lib"]
resolver = "2"

[profile.release]
lto = true
strip = "debuginfo"
codegen-units = 1

[workspace.dependencies]
roc_std = { git = "https://github.com/roc-lang/roc.git" }
