[package]
name = "roc_backend_host_lib"
version = "0.0.1"
edition = "2021"

[lib]
name = "host"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
roc_backend_host = { path = "../roc_backend_host" }
